// <auto-generated />
using System;
using Atelier.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atelier.Web.Data.Migrations
{
    [DbContext(typeof(AtelierDbContext))]
    [Migration("20260330053947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.Blocker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("KrUpdateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KrUpdateId");

                    b.HasIndex("WeeklyReportId");

                    b.ToTable("Blockers");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MonthlyPlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyPlanId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.KeyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("KeyResults");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.KrUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionNotes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KeyResultId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyResultId");

                    b.HasIndex("WeeklyReportId");

                    b.ToTable("KrUpdates");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.MonthlyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PlanMonth")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WorkspaceId", "PlanMonth", "IsPrimary")
                        .IsUnique();

                    b.ToTable("MonthlyPlans");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.MonthlyPlanRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationResult")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceGoalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIdentity")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceKeyResultId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceMonthlyPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SourceGoalId");

                    b.HasIndex("SourceIdentity");

                    b.HasIndex("SourceKeyResultId");

                    b.HasIndex("SourceMonthlyPlanId");

                    b.ToTable("MonthlyPlanRevisions");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.MonthlyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftConclusion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftRating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DraftedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalConclusion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalRating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FinalizedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MonthlyPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DraftedByUserId");

                    b.HasIndex("FinalizedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("MonthlyPlanId", "UserId")
                        .IsUnique();

                    b.ToTable("MonthlyReviews");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.UnlinkedWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WeeklyReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyReportId");

                    b.ToTable("UnlinkedWorkItems");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.WeeklyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDeadlineDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MonthlyPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextWeekPlan")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadOnlyAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReportingWeekStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklyProgress")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyPlanId");

                    b.HasIndex("UserId", "ReportingWeekStartDate")
                        .IsUnique();

                    b.ToTable("WeeklyReports");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.HolidayCalendarEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Date")
                        .IsUnique();

                    b.ToTable("HolidayCalendarEntries");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamLeadUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamLeadUserId");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnterpriseWeChatUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseWeChatUserId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.Blocker", b =>
                {
                    b.HasOne("Atelier.Web.Domain.PlanReview.KrUpdate", "KrUpdate")
                        .WithMany("Blockers")
                        .HasForeignKey("KrUpdateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atelier.Web.Domain.PlanReview.WeeklyReport", "WeeklyReport")
                        .WithMany("Blockers")
                        .HasForeignKey("WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KrUpdate");

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.Goal", b =>
                {
                    b.HasOne("Atelier.Web.Domain.PlanReview.MonthlyPlan", "MonthlyPlan")
                        .WithMany("Goals")
                        .HasForeignKey("MonthlyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.Platform.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonthlyPlan");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.KeyResult", b =>
                {
                    b.HasOne("Atelier.Web.Domain.PlanReview.Goal", "Goal")
                        .WithMany("KeyResults")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.Platform.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.KrUpdate", b =>
                {
                    b.HasOne("Atelier.Web.Domain.PlanReview.KeyResult", "KeyResult")
                        .WithMany("Updates")
                        .HasForeignKey("KeyResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.PlanReview.WeeklyReport", "WeeklyReport")
                        .WithMany("KrUpdates")
                        .HasForeignKey("WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyResult");

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.MonthlyPlan", b =>
                {
                    b.HasOne("Atelier.Web.Domain.Platform.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.Platform.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.MonthlyPlanRevision", b =>
                {
                    b.HasOne("Atelier.Web.Domain.Platform.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.PlanReview.Goal", "SourceGoal")
                        .WithMany()
                        .HasForeignKey("SourceGoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atelier.Web.Domain.PlanReview.KeyResult", "SourceKeyResult")
                        .WithMany()
                        .HasForeignKey("SourceKeyResultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atelier.Web.Domain.PlanReview.MonthlyPlan", "SourceMonthlyPlan")
                        .WithMany("Revisions")
                        .HasForeignKey("SourceMonthlyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("SourceGoal");

                    b.Navigation("SourceKeyResult");

                    b.Navigation("SourceMonthlyPlan");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.MonthlyReview", b =>
                {
                    b.HasOne("Atelier.Web.Domain.Platform.User", "DraftedByUser")
                        .WithMany()
                        .HasForeignKey("DraftedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atelier.Web.Domain.Platform.User", "FinalizedByUser")
                        .WithMany()
                        .HasForeignKey("FinalizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atelier.Web.Domain.PlanReview.MonthlyPlan", "MonthlyPlan")
                        .WithMany("MonthlyReviews")
                        .HasForeignKey("MonthlyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.Platform.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DraftedByUser");

                    b.Navigation("FinalizedByUser");

                    b.Navigation("MonthlyPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.UnlinkedWorkItem", b =>
                {
                    b.HasOne("Atelier.Web.Domain.PlanReview.WeeklyReport", "WeeklyReport")
                        .WithMany("UnlinkedWorkItems")
                        .HasForeignKey("WeeklyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyReport");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.WeeklyReport", b =>
                {
                    b.HasOne("Atelier.Web.Domain.PlanReview.MonthlyPlan", "MonthlyPlan")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("MonthlyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.Platform.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonthlyPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.AuditLog", b =>
                {
                    b.HasOne("Atelier.Web.Domain.Platform.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atelier.Web.Domain.Platform.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.HolidayCalendarEntry", b =>
                {
                    b.HasOne("Atelier.Web.Domain.Platform.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.Team", b =>
                {
                    b.HasOne("Atelier.Web.Domain.Platform.User", "TeamLeadUser")
                        .WithMany()
                        .HasForeignKey("TeamLeadUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atelier.Web.Domain.Platform.Workspace", "Workspace")
                        .WithMany("Teams")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamLeadUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.User", b =>
                {
                    b.HasOne("Atelier.Web.Domain.Platform.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atelier.Web.Domain.Platform.Workspace", "Workspace")
                        .WithMany("Users")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.Goal", b =>
                {
                    b.Navigation("KeyResults");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.KeyResult", b =>
                {
                    b.Navigation("Updates");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.KrUpdate", b =>
                {
                    b.Navigation("Blockers");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.MonthlyPlan", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("MonthlyReviews");

                    b.Navigation("Revisions");

                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("Atelier.Web.Domain.PlanReview.WeeklyReport", b =>
                {
                    b.Navigation("Blockers");

                    b.Navigation("KrUpdates");

                    b.Navigation("UnlinkedWorkItems");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Atelier.Web.Domain.Platform.Workspace", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
